#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joy.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Include.cshtml")]
    public partial class Include : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Include()
        {
        }
        public override void Execute()
        {
WriteLiteral("<link");

WriteLiteral(" href=\"/res/Joy.Web.Content.reset.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<script");

WriteLiteral(" src=\"/res/Joy.Web.Scripts.Common.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n<script");

WriteLiteral(" src=\"/res/Joy.Web.Scripts.jquery-1.10.2.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n<script");

WriteLiteral(" src=\"/res/Joy.Web.Scripts.jquery.json.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n<script");

WriteLiteral(" src=\"/res/Joy.Web.Scripts.jquery.form.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n<script");

WriteLiteral(" src=\"/res/Joy.Web.Scripts.jquery.dom.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n<script");

WriteLiteral(" src=\"/res/Joy.Web.Scripts.jquery.cookies.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n<script");

WriteLiteral(" src=\"/res/Joy.Web.Scripts.Security.AES.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n                   \r\n<link");

WriteLiteral(" href=\"/res/Joy.Web.Content.controls.cell.cell_color.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/res/Joy.Web.Content.controls.cell.cell_layout.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/res/Joy.Web.Content.controls.uploader.uploader_color.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/res/Joy.Web.Content.controls.uploader.uploader_layout.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<script");

WriteLiteral(" src=\"/res/Joy.Web.Scripts.controls.cell.Cell.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n<script");

WriteLiteral(" src=\"/res/Joy.Web.Scripts.jquery.upload.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n<script");

WriteLiteral(" src=\"/res/Joy.Web.Scripts.jquery.request.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n");

        }
    }
}
#pragma warning restore 1591
