#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joy.Web.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SinglePage.cshtml")]
    public partial class SinglePage : System.Web.Mvc.WebViewPage<dynamic>
    {
        public SinglePage()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\SinglePage.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n");

WriteLiteral("        ");

            
            #line 7 "..\..\Views\SinglePage.cshtml"
   Write(Html.Partial("~/Views/Include.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 8 "..\..\Views\SinglePage.cshtml"
   Write(RenderSection("CSS", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 9 "..\..\Views\SinglePage.cshtml"
   Write(RenderSection("JS", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </head>\r\n    <body");

WriteLiteral(" class=\"debug\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Views\SinglePage.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("        \r\n    </body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
